## Linear independence

### Linear dependence

A collection or list of $n$-vectors $a_{1},\ldots,a_{k}$ (with $k\geq 1$) is called _linearly dependent_ if

$$ \beta_{1}a_{1}+\cdots+\beta_{k}a_{k}=0 $$

holds for some $\beta_{1},\ldots,\beta_{k}$ that are not all zero. In other words, we can form the zero vector as a linear combination of the vectors, with coefficients that are not all zero. Linear dependence of a list of vectors does not depend on the ordering of the vectors in the list.

#### Linear combinations of linearly independent vectors.

Suppose a vector $x$ is a linear combination of $a_1, \ldots, a_k$,
$$
x=\beta_1 a_1+\cdots+\beta_k a_k .
$$

When the vectors $a_1, \ldots, a_k$ are linearly independent, the coefficients that form $x$ are unique: If we also have
$$
x=\gamma_1 a_1+\cdots+\gamma_k a_k
$$
then $\beta_i=\gamma_i$ for $i=1, \ldots, k$. This tells us that, in principle at least, we can find the coefficients that form a vector $x$ as a linear combination of linearly independent vectors.

### Basis
#### Independence-dimension inequality.
If the $n$-vectors $a_1, \ldots, a_k$ are linearly independent, then $k \leq n$. In words:
> A linearly independent collection of $n$-vectors can have at most $n$ elements.

Put another way:
>Any collection of $n+1$ or more n-vectors is linearly dependent.

As a very simple example, we can conclude that any three 2 -vectors must be linearly dependent.
We will prove this fundamental fact below; but first, we describe the concept of basis, which relies on the independence-dimension inequality.

#### Basis.

A collection of $n$ linearly independent $n$-vectors (i.e., a collection of linearly independent vectors of the maximum possible size) is called a **basis**.

If the $n$-vectors $a_1, \ldots, a_n$ are a basis, then any $n$-vector $b$ can be written as a linear combination of them. To see this, consider the collection of $n+1$ $n$-vectors $a_1, \ldots, a_n, b$. By the independence-dimension inequality, these vectors are linearly dependent, so there are $\beta_1, \ldots, \beta_{n+1}$, not all zero, that satisfy
$$
\beta_1 a_1+\cdots+\beta_n a_n+\beta_{n+1} b=0
$$

If $\beta_{n+1}=0$, then we have
$$
\beta_1 a_1+\cdots+\beta_n a_n=0
$$
which, since $a_1, \ldots, a_n$ are linearly independent, implies that $\beta_1=\cdots=\beta_n=0$. But then all the $\beta_i$ are zero, a contradiction. So we conclude that $\beta_{n+1} \neq 0$. It follows that
$$
b=\left(-\beta_1 / \beta_{n+1}\right) a_1+\cdots+\left(-\beta_n / \beta_{n+1}\right) a_n
$$
i.e., $b$ is a linear combination of $a_1, \ldots, a_n$.

Combining this result with the observation above that any linear combination of linearly independent vectors can be expressed in only one way, we conclude:

> Any $n$-vector $b$ can be written in a unique way as a linear combination of a basis $a_1, \ldots, a_n$.

#### Expansion in a basis.

When we express an $n$-vector $b$ as a linear combination of a basis $a_1, \ldots, a_n$, we refer to
$$
b=\alpha_1 a_1+\cdots+\alpha_n a_n
$$
as the expansion of $b$ in the $a_1, \ldots, a_n$ basis. The numbers $\alpha_1, \ldots, \alpha_n$ are called the coefficients of the expansion of $b$ in the basis $a_1, \ldots, a_n$.

#### Examples

- The $n$ standard unit $n$ vectors $e_1, \ldots, e_n$ are a basis. Any $n$-vector $b$ can be written as the linear combination
$$
b=b_1 e_1+\cdots+b_n e_n .
$$
This expansion is unique, which means that there is no other linear combination of $e_1, \ldots, e_n$ that equals $b$.
- The vectors
$$
a_1=\left[\begin{array}{r}
1.2 \\
-2.6
\end{array}\right], \quad a_2=\left[\begin{array}{l}
-0.3 \\
-3.7
\end{array}\right]
$$
are a basis. The vector $b=(1,1)$ can be expressed in only one way as a linear combination of them:
$$
b=0.6513 a_1-0.7280 a_2 .
$$
(The coefficients are given here to 4 significant digits. We will see later how these coefficients can be computed.)

### Orthonormal vectors

A collection of vectors $a_1, \ldots, a_k$ is orthogonal or mutually orthogonal if $a_i \perp a_j$ for any $i, j$ with $i \neq j, i, j=1, \ldots, k$. A collection of vectors $a_1, \ldots, a_k$ is orthonormal if it is orthogonal and $\left\|a_i\right\|=1$ for $i=1, \ldots, k$. (A vector of norm one is called normalized; dividing a vector by its norm is called normalizing it.) Thus, each vector in an orthonormal collection of vectors is normalized, and two different vectors from the collection are orthogonal. These two conditions can be combined into one statement about the inner products of pairs of vectors in the collection: $a_1, \ldots, a_k$ is orthonormal means that
$$
a_i^T a_j= \begin{cases}1 & i=j \\ 0 & i \neq j .\end{cases}
$$

Orthonormality, like linear dependence and independence, is an attribute of a collection of vectors, and not an attribute of vectors individually. By convention, though, we say "The vectors $a_1, \ldots, a_k$ are orthonormal" to mean "The collection of vectors $a_1, \ldots, a_k$ is orthonormal".

In [ ]:
import numpy as np
import numpy.linalg as npl
import matplotlib.pyplot as plt

In [ ]:
a1 = np.array([0, 0, -1])
a2 = np.array([1, 1, 0]) / np.sqrt(2)
a3 = np.array([1, -1, 0]) / np.sqrt(2)

print(
    f"norm a1: {npl.norm(a1)}, \nnorm a2: {npl.norm(a2)}, \nnorm a3: {npl.norm(a3)}\n"
    f"inner product a1a2: {np.inner(a1, a2)}, \ninner product a1a3: {np.inner(a1, a3)}"
)

norm a1: 1.0, 
norm a2: 0.9999999999999999, 
norm a3: 0.9999999999999999
inner product a1a2: 0.0, 
inner product a1a3: 0.0


In [ ]:
x = np.array([1, 2, 3])

beta1 = np.inner(a1, x)
beta2 = np.inner(a2, x)
beta3 = np.inner(a3, x)

xexp = beta1 * a1 + beta2 * a2 + beta3 * a3
print(
    f"expansion {xexp}\n"
    f"original {x}\n"
)

expansion [1. 2. 3.]
original [1 2 3]



### Gram–Schmidt algorithm

**Algorithm:** given $n$-vectors $a_1, \ldots, a_k$ for $i=1, \ldots, k$,
1. Orthogonalization. $\tilde{q}_i=a_i-\left(q_1^T a_i\right) q_1-\cdots-\left(q_{i-1}^T a_i\right) q_{i-1}$
2. Test for linear dependence. if $\tilde{q}_i=0$, quit.
3. Normalization. $q_i=\tilde{q}_i /\left\|\tilde{q}_i\right\|$

In [ ]:
def gram_schmidt(a, tol=1e-10):
    q = []
    for i in range(len(a)):
        qtilde = a[i]

        for j in range(i):
            qtilde = qtilde - np.inner(q[j], a[i]) * q[j]

        if npl.norm(qtilde) < tol:
            print("Vectors linearly dependent")

        q.append(qtilde / npl.norm(qtilde))
    return q

In [ ]:
a = np.array([[-1, 1, -1, 1], [-1, 3, -1, 3], [1, 3, 5, 7]])
q = gram_schmidt(a)
print(f"The orthonormal vectors are:\n{q}")
print(f"Norms of vectors {np.linalg.norm(q, axis=1)}")

The orthonormal vectors are:
[[-0.5         0.5        -0.5         0.5       ]
 [ 0.57539646 -0.41099747  0.57539646 -0.41099747]
 [ 0.58171796 -0.39099076  0.6198634  -0.35284532]]
Norms of vectors [1. 1. 1.]


## Matrices


In [ ]:
A = np.matrix([[0.0, 1.0, -2.3, 0.1], [1.3, 4.0, -0.1, 0.0],[4.1,-1.0, 0.0, 1.7]])
B = np.array([[0.0, 1.0, -2.3, 0.1], [1.3, 4.0, -0.1, 0.0],[4.1,-1.0, 0.0, 1.7]])
print(type(A))
print(type(B))
print(np.array_equal(A, B))
B[2][0] = 0.
print(np.array_equal(A, B))
A == B

<class 'numpy.matrix'>
<class 'numpy.ndarray'>
True
False


matrix([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [False,  True,  True,  True]])

In [ ]:
A[:,2]

matrix([[-2.3],
        [-0.1],
        [ 0. ]])

In [ ]:
A.flatten()

matrix([[ 0. ,  1. , -2.3,  0.1,  1.3,  4. , -0.1,  0. ,  4.1, -1. ,
          0. ,  1.7]])

In [ ]:
A.reshape(-1)

matrix([[ 0. ,  1. , -2.3,  0.1,  1.3,  4. , -0.1,  0. ,  4.1, -1. ,
          0. ,  1.7]])

In [ ]:
A.reshape(4, 3)

matrix([[ 0. ,  1. , -2.3],
        [ 0.1,  1.3,  4. ],
        [-0.1,  0. ,  4.1],
        [-1. ,  0. ,  1.7]])

In [ ]:
np.concatenate((A, A[:, 0]), axis=1)

matrix([[ 0. ,  1. , -2.3,  0.1,  0. ],
        [ 1.3,  4. , -0.1,  0. ,  1.3],
        [ 4.1, -1. ,  0. ,  1.7,  4.1]])

In [ ]:
np.block([A, B])

matrix([[ 0. ,  1. , -2.3,  0.1,  0. ,  1. , -2.3,  0.1],
        [ 1.3,  4. , -0.1,  0. ,  1.3,  4. , -0.1,  0. ],
        [ 4.1, -1. ,  0. ,  1.7,  0. , -1. ,  0. ,  1.7]])

In [ ]:
A.transpose()

array([[ 0, -2],
       [ 2,  1],
       [-1,  1]])

In [ ]:
np.linalg.norm(A)

3.3166247903554

### Zero and identity matrices

In [ ]:
A = np.zeros((2,2))
# A = np.identity(4)
# A = np.diag([1,2,3])
A

array([[0., 0.],
       [0., 0.]])

#### Sparse matrices.

A matrix $A$ is said to be sparse if many of its entries are zero, or (put another way) just a few of its entries are nonzero. Its sparsity pattern is the set of indices $(i, j)$ for which $A_{i j} \neq 0$. The number of nonzeros of a sparse matrix $A$ is the number of entries in its sparsity pattern, and denoted $\mathbf{n n z}(A)$. If $A$ is $m \times n$ we have $\mathbf{n n z}(A) \leq m n$. Its density is $\mathbf{n n z}(A) /(m n)$, which is no more than one. Densities of sparse matrices that arise in applications are typically small or very small, as in $10^{-2}$ or $10^{-4}$.

There is no precise definition of how small the density must be for a matrix to qualify as sparse. A famous definition of sparse matrix due to the mathematician James H. Wilkinson is: A matrix is sparse if it has enough zero entries that it pays to take advantage of them. Sparse matrices can be stored and manipulated efficiently on a computer.

In [ ]:
from scipy.sparse import csc_matrix

row_pos = np.array([0, 2, 2, 0, 1, 2])
col_pos = np.array([0, 0, 1, 2, 2, 2])
data = np.array([1, 2, 3, 4, 5, 6])

csc_matrix((data, (row_pos, col_pos)), shape=(3, 3)).nnz

6

### Matrix-vector multiplication



In [ ]:
A = np.array([[0, 2, -1], [-2, 1, 1]])
x = np.array([2, 1, -1])
np.matmul(A, x)

array([ 3, -4])

#### Application examples

> __Feature matrix and weight vector.__ Suppose $X$ is a feature matrix, where its $N$ columns $x_1, \ldots, x_N$ are feature $n$-vectors for $N$ objects or examples. Let the $n$-vector $w$ be a weight vector, and let $s_i=x_i^T w$ be the score associated with object $i$ using the weight vector $w$. Then we can write $s=X^T w$, where $s$ is the $N$-vector of scores of the objects.

> __Polynomial evaluation at multiple points.__ Suppose the entries of the $n$-vector $c$ are the coefficients of a polynomial $p$ of degree $n-1$ or less:
$$
p(t)=c_1+c_2 t+\cdots+c_{n-1} t^{n-2}+c_n t^{n-1} .
$$
>
> Let $t_1, \ldots, t_m$ be $m$ numbers, and define the $m$-vector $y$ as $y_i=p\left(t_i\right)$. Then we have $y=A c$, where $A$ is the $m \times n$ matrix
$$
A=\left[\begin{array}{ccccc}
1 & t_1 & \cdots & t_1^{n-2} & t_1^{n-1} \\
1 & t_2 & \cdots & t_2^{n-2} & t_2^{n-1} \\
\vdots & \vdots & & \vdots & \vdots \\
1 & t_m & \cdots & t_m^{n-2} & t_m^{n-1}
\end{array}\right]
$$
>
> So multiplying a vector $c$ by the matrix $A$ is the same as evaluating a polynomial with coefficients $c$ at $m$ points. The matrix $A$ in (6.7) comes up often, and is called a Vandermonde matrix (of degree $n-1$, at the points $t_1, \ldots, t_m$ ), named for the mathematician Alexandre-Théophile Vandermonde.

In [ ]:
x = np.array([1, 2, 3, 5])
N = 3
B = np.vander(x, N)
B[:, -1::-1]

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  5, 25]])

> __Total price from multiple suppliers.__ Suppose the $m \times n$ matrix $P$ gives the prices of $n$ goods from $m$ suppliers (or in $m$ different locations). If $q$ is an $n$-vector of quantities of the $n$ goods (sometimes called a basket of goods), then $c=P q$ is an $N$-vector that gives the total cost of the goods, from each of the $N$ suppliers.

> Document scoring. Suppose $A$ in an $N \times n$ document-term matrix, which gives the word counts of a corpus of $N$ documents using a dictionary of $n$ words, so the rows of $A$ are the word count vectors for the documents. Suppose that $w$ in an $n$-vector that gives a set of weights for the words in the dictionary. Then $s=A w$ is an $N$-vector that gives the scores of the documents, using the weights and the word counts. A search engine, for example, might choose $w$ (based on the search query) so that the scores are predictions of relevance of the documents (to the search).

> Audio mixing. Suppose the $k$ columns of $A$ are vectors representing audio signals or tracks of length $T$, and $w$ is a $k$-vector. Then $b=A w$ is a $T$-vector representing the mix of the audio signals, with track weights given by the vector $w$.